### PR TITLE
Login with email too

### PR DESCRIPTION
**Pull request by aviaryan**
See #202 

One concern maybe that how login is done in case of users with same emails (assuming it is a feature). But there shouldn't be any problems as the query first matches the login (username) and then the email.

### CODE REVIEW

**Comment by aviaryan** [comment]
The second commit takes care of unlikely scenario where a user uses email of another user as his/her username (aka login). Also users with same emails can now login with their email itself (the password plays the distinguisher).

**Comment by leto** [comment]
If I register two new accounts, both with the same email and password, then login with an email and password, the first account is logged into. I think it is a bug that we allow somebody to register with an email that is already registered. If we fix that, the above problem goes away. Do you want to submit a PR for that?

Also, the UI might want to say "Login or Email" so that users know they can use either.

**Comment by aviaryan** [comment]
> I think it is a bug that we allow somebody to register with an email that is already registered.

I agree. PR #227

**Comment by leto** [comment]
Now that email is unique, this is solid

**Comment by leto** [comment]
Thanks!

**Pull request merged**
