### PR TITLE
Added Map to Event

### PR DESCRIPTION
**Pull request by aditya1702**
#368 
map2

### CODE REVIEW

**Comment by rafalkowalski** [comment]
Great! Put Map on the right. 
Fill Location field dynamically.(Moving markerker), Or if you put info to Location automatically marker should be changed
Remove geocode.

**Comment by aditya1702** [comment]
@rafalkowalski I was thinking if we could keep the geocode? It would be a nice feature

**Comment by rafalkowalski** [comment]
Location filed it will work like geocode so we don't need a geocode

**Comment by rafalkowalski** [comment]
@aditya1702 is it ok?

**Comment by aditya1702** [comment]
@rafalkowalski Yes. Although I can seem to move the map to the right. Could you merge it and do it?

**Pull request merged**
