### PR TITLE
Add field_identifier of custom form to attribute section in docs

### LINKED ISSUE #4291: Missing field name for field in custom forms API
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

- There is a field missing for the name of the field in the custom forms API
- The attributes section & the attributes in response do not match

### PR DESCRIPTION
**Pull request by enigmaeth**
Fixes #4291.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by enigmaeth** [comment]
@geekyd Can you please confirm if this was the issue :) ?

**Comment by geekyd** [comment]
@enigmaeth We need a `field` attribute which will be used to store the name of the field.

**Comment by enigmaeth** [comment]
@niranjan94 Can you take a look at the issue please? #4291.

**Comment by niranjan94** [comment]
I think this should do for now. The identifier would store the name of the field.

**Pull request merged**
