### PR TITLE
Provide proper content-type for s3 upload

### LINKED ISSUE #2424: Content type of images stored in AmazonS3 bucket is `application/octet-stream`
e.g.
https://opevbucketname.s3.amazonaws.com/events/179/speakers/1263/photo/MFhNSk9yRU/HansBakker_111.jpg has the content type `application/octet-stream` instead of `image/jpeg`.

Following is the response header for the specified file:

```
Accept-Ranges →bytes
Content-Disposition →attachment; filename=HansBakker_111.jpg
Content-Length →56060
Content-Type →application/octet-stream
Date →Fri, 09 Sep 2016 10:51:06 GMT
ETag →"964b1d839a9261fb0b159e960ceb4cf9"
Last-Modified →Tue, 06 Sep 2016 05:06:23 GMT
Server →AmazonS3
x-amz-id-2 →1GnO0Ta1e+qUE96Qgjm5ZyfyuhMetjc7vfX8UWEsE4fkZRBAuGx9gQwozidTroDVO/SU3BusCZs=
x-amz-request-id →ACF274542E950116
```

### PR DESCRIPTION
**Pull request by shubham-padia**
Attempts to resolve #2424 .
Library used : https://github.com/ahupp/python-magic

Sample image with proper Content-Type : 
https://s3-us-west-2.amazonaws.com/opevorga/events/1/background/WUdDYkdNc0/1475011859.25.png

### CODE REVIEW

**Comment by aviaryan** [comment]
@shubham-padia Looks good. Just one thing, are there any external dependencies required to run Magic on Linux. In python-magic's README, I see it [requires some binaries](https://github.com/ahupp/python-magic#dependencies) to run. Since Linux has not been mentioned in the list, I wonder what is required on linux to run it. As the Docker deployment is based on linux (ubuntu), adding a library with external binary dependencies has chances of breaking the docker orga-server.

**Comment by shubham-padia** [comment]
@aviaryan On my system, no external binaries were required for linux, just `pip install` worked fine.

**Comment by aviaryan** [comment]
@shubham-padia Maybe it requires some binary that is already a part of ubuntu. But Docker ubuntu is different from your ubuntu so it may still lack that binary, that's why I asked. Can you try running and testing Docker version of Open Event in your system, just to be sure..

**Comment by aviaryan** [comment]
Never mind, I ran docker version of open event on my system and tried using python-magic. It didn't work because libmagic was missing. One can fix that by installing libmagic-dev on their system. 

Add `libmagic-dev` in the list of libraries to install in Dockerfile L14. https://github.com/fossasia/open-event-orga-server/blob/development/Dockerfile#L14

**Comment by shubham-padia** [comment]
@aviaryan  Added `libmagic-dev` to Dockerfile. Please review again.

**Comment by aviaryan** [comment]
Thanks @shubham-padia :smile:

**Pull request merged**
