### PR TITLE
Fixes: Creating an event with logo does not work. #178

### PR DESCRIPTION
**Pull request by suheb**
Also some improvements in UI and update_event().

Signed-off-by: Suhaib Khan <suhebjerk@gmail.com>

### CODE REVIEW

**Comment by aditya1702** [comment]
@suheb I saw your commit.I have already made the same changes except the list.html one. I think its good:)

**Comment by suheb** [comment]
@leto Hey, can you review this. I think we're good to go here.

**Comment by suheb** [comment]
@leto @creativepsyco bump.

**Comment by leto** [comment]
Looks like we have merge conflicts, can you please update this PR? Thanks

**Comment by suheb** [comment]
@leto Done.

**Comment by suheb** [comment]
Closing as this is effectively fixed by [this](https://github.com/fossasia/open-event-orga-server/commit/45771fd5f294545e72c777feffb1cece0a110132)

**Pull request closed without merging**
