### PR TITLE
Import event from json

### LINKED ISSUE #774: Import Event: Create event from exported json
Parent Issue: #728 
Export event: #758 (PR = #772)

A POST request with the jsons zip file to `api/v2/events/import/json` will create the event along with other services (sessions, speakers and so) and return the newly created event as response.

### PR DESCRIPTION
**Pull request by aviaryan**
Fixes #774 

The url is `api/v2/events/import/json`
Send there a POST request with the zip file named 'file' .
Returns the newly created event data on success.

#### Sample requests code for uploading

```python
from requests import post
files = {'file': open('event1.zip','rb')}
r = post(url + '/import/json', files=files, auth=('super_admin@gmail.com', 'test'))
print r, r.content
```

I have attached a sample event below for anyone to test it.
[event1.zip](https://github.com/fossasia/open-event-orga-server/files/313147/event1.zip)

### CODE REVIEW

**Comment by aviaryan** [comment]
@mariobehling @shivamMg please review

**Comment by mariobehling** [comment]
@aviaryan I don't understand the structure of this file. There are several JSON files inside that do not seem to make sense. Is this reflecting the current API structure? 
screenshot from 2016-06-14 08 02 30
Where did you come up with this? Where is the documentation regarding it?

**Comment by shivamMg** [comment]
@mariobehling All them come under the APIs. https://open-event.herokuapp.com/api/v2/

Sponsor Type was added later: https://github.com/fossasia/open-event-orga-server/issues/674
Rest all were already defined.

**Comment by mariobehling** [comment]
@aviaryan This does not make sense, e.g. why do we have different APIs for sponsors and sponsor types?

**Comment by mariobehling** [comment]
This is a big mess! Omg!

All APIs were defined in issues here https://github.com/fossasia/open-event-orga-server/issues?q=is%3Aopen+label%3A%22parent+issue%22+label%3ARest-API

I am still waiting for progress here, but now I see this mess of APIs for single fields like sponsorship levels. So, the sponsorship level, one field, gets its own API. Fantastic!

**Comment by shivamMg** [comment]
@mariobehling I've created the Sponsor type models and apis. Sponsor Types are specific to an event. An event organizer can create sponsor types (like "Platinum Sponsor", "Gold Sponsor", etc.) and then associate Sponsors to these types. Sponsor Type is an attribute of a Sponsor, to make it extensible (provide more than just some defined values) it needed models and apis.

**Comment by mariobehling** [comment]
@shivamMg We talked about this here https://github.com/fossasia/open-event-orga-server/issues/624 The examples in the OpenTechSummit are not complete, but they clearly direct us to where we need to go. The sample JSONs are still here https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/json

**Comment by shivamMg** [comment]
@mariobehling I made the changes to make Sponsor database model to be consistent with the define json. Every Sponsor has a `type` property ([eg](https://github.com/OpenTechSummit/2016.opentechsummit.net/blob/gh-pages/programm/json/sponsors.json#L8)). The value of `type` can be same for two different sponsors in an event ([eg1](https://github.com/OpenTechSummit/2016.opentechsummit.net/blob/gh-pages/programm/json/sponsors.json#L35), [eg2](https://github.com/OpenTechSummit/2016.opentechsummit.net/blob/gh-pages/programm/json/sponsors.json#L44)). To think of it in the UI, when an organizer would be entering Type field in the Sponsor form he would get a list of choices (drop-down field). These choices would be the ones that he specified using SponsorTypes.

**Comment by mariobehling** [comment]
I am merging this PR as the import part seems fine. However, the JSON itself do not make sense. If we continue that path, we will have dozens of APIs and a super complicated way of doing things. You wrote e week ago:

> We need to define the fields at the database models first and reflect the same at the APIs. Models that require changes are Tracks, Sessions and Sponsors. I guess working on one model at a time would be best. https://github.com/fossasia/open-event-orga-server/issues/624#issuecomment-224382530

I do not see that this has been even started yet. There is no progress in these issues, but you keep opening some issues for a quick implementation of something that has not been thought through whereas there are no comments in the parent issues where we outlined the required APIs. 

Please start now and outline each API clearly. Please do keep it simple. I have created a "super parent issue". If there is any other API to be defined, please add it in the list, but first discuss if other APIs are absolutely necessary and why: https://github.com/fossasia/open-event-orga-server/issues/799

**Pull request merged**
