### PR TITLE
Session details shown on expand in tracks view

### LINKED ISSUE #3259: Tracks Page does not show additional info
Sessions on the tracks page are supposed to show additional info on clicking on the specific session (similar to web app and sessions view). Currently the area does not expand on clicking it.

screenshot from 2017-02-26 15-00-30

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #3259 

screenshot from 2017-03-05 16-11-23

@mariobehling @niranjan94 please review

### CODE REVIEW

**Comment by mariobehling** [comment]
I think the speaker details are not included yet, but let's iterate from here and get this to Master asap.

**Comment by SaptakS** [comment]
@mariobehling Yes. The speaker details are not included. We can iterate over by exactly defining what all are needed to be shown on expanding.

**Comment by mariobehling** [comment]
> what all are needed to be shown on expanding.

Same as web app.

**Comment by mariobehling** [comment]
Please merge to master.

**Pull request merged**
