### PR TITLE
handle sessions/speakers added by admin

### LINKED ISSUE #3102: How should organizer add sessions of speakers with existing email addresses
A question: We want to sign up speakers for a session who are not added to the event yet. However, the email address of the speakers was used to get a ticket already. Can I add these speakers to the event and ensure that is shows up in the speakers account?

I can go to "https://eventyay.com/events/6/sessions/" and create a session, but even if I add another email address, I see that the session shows up under "My sessions" in my account. Whereas it should show up in the speakers account.

What is the best approach?

### PR DESCRIPTION
**Pull request by niranjan94**
Resolves #3102

When an organizer adds a session or a speaker from `/events/<event_id>/sessions` or `/events/<event_id>/speakers`

The session/speaker is linked to the already existing user. (searched by email). if a user with that email, does not exisit, the user is created automatically and an email is sent with username and a temp. password.

### CODE REVIEW

**Comment by niranjan94** [comment]
@mariobehling please review and merge

**Comment by mariobehling** [comment]
@niranjan94 Will this also take care of the existing sessions, that are associated with the wrong account?

This fix needs to get into master asap.

**Comment by mariobehling** [comment]
> The command "python manage.py initialize_db -c open_event_test_user@fossasia.org:fossasia" failed and exited with 1 during .

Travis failing.

**Comment by niranjan94** [comment]
@mariobehling yes. It will take care of the existing sessions too

**Pull request merged**
