### PR TITLE
I650 UI of index side added

### PR DESCRIPTION
**Pull request by rafalkowalski**
#650 Index Page UI added 

@mariobehling @SaptakS @niranjan94

### CODE REVIEW

**Comment by rafalkowalski** [comment]
screen shot 2016-06-09 at 21 53 26
screen shot 2016-06-09 at 21 53 37

**Comment by mariobehling** [comment]
Very nice! Looks excellent.

**Comment by mariobehling** [comment]
Please add an "s" at the end of the tagline:
The simplest way to create events

**Comment by SaptakS** [comment]
Seems good to merge. Merging.

**Pull request merged**
