### PR TITLE
add flask-migrate dependency

### PR DESCRIPTION
**Pull request by championswimmer**
@leto @rafalkowalski @creativepsyco

### CODE REVIEW

**Comment by creativepsyco** [comment]
I think instead of this we should simply do: 

```bash
pip install -r requirements.txt 
```

Of course after python and pip packages are installed. Let's not do duplicate stuff. Also please set assignee for the PR, mentioning usernames in comments sounds laziness to me :unamused: 

image

**Comment by creativepsyco** [comment]
@rafalkowalski can we instead just add the above line `pip install -r requirements.txt ` in the `install.sh` file then we don't need to add dependencies explicitly and have double code just to install the dependencies? 

Did you understand my point?

**Comment by rafalkowalski** [comment]
@creativepsyco I will add it ;)

**Comment by leto** [comment]
Just saw this. We must absolutely use ```pip install -r requirements.txt ```. We also must freeze our dependency versions with ```pip freeze```

**Pull request merged**
