### PR TITLE
email message displayed

### LINKED ISSUE #2799: Add email confirmation message "Email has been sent.." to ticketing confirmation
If a user orders a ticket, there is a confirmation page.

Please add a message on top "An email with the ticket has also been sent to your email account."

screenshot from 2016-12-31 16-36-17

### PR DESCRIPTION
**Pull request by magdalenesuo**
fixed #2799
screenshot from 2017-01-03 00-48-01

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

The "full stop" is missing. As we are mentioning two times "email", please also change the message as follows:

An email with the ticket has also been sent to your email account.

**Comment by magdalenesuo** [comment]
@mariobehling okay. I'll make the changes.

**Comment by magdalenesuo** [comment]
@mariobehling I've made the changes. Please review

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
