### PR TITLE
Changed the 'Published on' position and added event name to scheduler

### PR DESCRIPTION
**Pull request by LuD1161**
Done changes.
Solved #3339 

image

### CODE REVIEW

**Comment by LuD1161** [comment]
@SaptakS 
It's done
screenshot from 2017-03-10 16-22-12

**Comment by SaptakS** [comment]
@LuD1161 it still doesn't seem fixed. Also, it is now a lot below... It should be in the same top level as timezone and same left level as schedule.

**Comment by LuD1161** [comment]
@SaptakS 
It's Done , hopefully

**Comment by niranjan94** [comment]
@LuD1161 along with @SaptakS 's comments, also squash your commits into one.

**Comment by LuD1161** [comment]
@niranjan94 

It's done.

image

**Pull request merged**
