### PR TITLE
Add kubernetes config for android generator

### PR DESCRIPTION
**Pull request by niranjan94**
Resolves https://github.com/fossasia/open-event-android/issues/945

### CODE REVIEW

**Comment by mariobehling** [comment]
Is it a good idea to include this in this repo? Would it be possible to add another key and do this from the Android repo itself?

**Comment by niranjan94** [comment]
@mariobehling since we had all the kubernetes config here, Thought I'd put it here ... But yes, it is possible to move to the android app repo. I'll do it.

**Comment by mariobehling** [comment]
ok, thanks. As these repos are separated the deployment should be separated for now. (I hope it is the right strategy.)

Please get Harshit on board and give him access to the cloud deployment of the Android app. Thank you.

**Comment by niranjan94** [comment]
Agreed. Let's keep the deployments separate. Since and android app deployments is not gonna affect eventyay deployments in any way.

@mariobehling yes. harshit and myself have been discussing about this

**Pull request closed without merging**
