### PR TITLE
Modules UI modified

### PR DESCRIPTION
**Pull request by rafalkowalski**
#1875 @niranjan94 @mariobehling please review
modules open event

- [x]  Adjust /admin/modules/ to the style of other pages including font size, boldness or normal, height and style of heading

### CODE REVIEW

**Comment by niranjan94** [comment]
@rafalkowalski could you center the text vertically ?

**Comment by mariobehling** [comment]
* [ ] Move Save button to the bottom right below table as outlined in the issue itself.

**Comment by niranjan94** [comment]
@rafalkowalski could you add a screenshot ?

**Comment by rafalkowalski** [comment]
modules open event
settings open event

**Pull request merged**
