### PR TITLE
Fixes: Allows uploading multiple files with the same name #175

### PR DESCRIPTION
**Pull request by suheb**
Signed-off-by: Suhaib Khan <suhebjerk@gmail.com>

### CODE REVIEW

**Comment by leto** [comment]
Looks like we have merge conflicts, could you update this PR please?

**Comment by suheb** [comment]
@leto Done.

**Comment by suheb** [comment]
@leto I think we're good to go here.

**Comment by leto** [comment]
Thanks for being persistent :+1:

**Comment by leto** [comment]
Am I correct in seeing that http://127.0.0.1:8001/admin/event/upload is only available by typing in the URL? Does any page actually link to it anymore?

**Comment by rafalkowalski** [comment]
@creativepsyco @leto I think that uploading files is not necessary. We had a huge problem in Heroku with storing files, so we decided that we don't need this. I only save a link to database

**Pull request merged**
