### PR TITLE
API endpoints added

### PR DESCRIPTION
**Pull request by SaptakS**
@championswimmer @mananwason added API endpoints `/events/ID/event/` to return the same values as `events/ID/`. Please review.

### CODE REVIEW

**Comment by SaptakS** [comment]
Will get the build fixed ASAP.

**Comment by shivamMg** [comment]
@SaptakS No need to create a new class again. You can just add a new path to the `@api.route` decorator.

```python
@api.route('/<int:event_id>', '/<int:event_id>/event')
```

But then why do we need it. It doubles the get, delete and put APIs for Events.

**Comment by championswimmer** [comment]
@shivamMg 
When we used a file based API (like saving the jsons to a folder on github), then event/:id is a folder, so we save the event.json in event/:id/event.json

The API matching that would make it consistent. That's it

**Comment by shivamMg** [comment]
@SaptakS You need to define only the `get` method for the class. As @championswimmer said, only the GET method is required. The reason we cannot just add a new path (like I said above) is because routes are defined for Resource classes and not individual methods.

```python
@api.route('/<int:event_id>/event')
@api.param('event_id')
@api.response(404, 'Event not found')
class EventWebapp(Resource):
    @api.doc('get_event_for_webapp') # should be unique
    @api.marshal_with(EVENT)
    def get(self, event_id):
        """Fetch an event given its id.
        Alternate endpoint for fetching an event.
        """
        return DAO.get(event_id)
```

**Comment by SaptakS** [comment]
@championswimmer @shivamMg please review

**Pull request merged**
