### PR TITLE
Fix Incorrect calculation of discounts if cost is less than 1USD

### LINKED ISSUE #2876: Incorrect calculation of discounts if cost is less than 1USD
If I enter 99% or 41.50USD discount of a 42USD ticket, the ticketing system does not calculate Cents. It is also not possible to give 20.50 USD discount.

Expected: Please ensure, Cents and other currencies, that use discounts that result in anything behind the fullstop (or comma) are calculated as well.

### PR DESCRIPTION
**Pull request by satwikkansal**
Resolves #2876

screenshot from 2017-01-09 23-56-03
screenshot from 2017-01-11 02-31-35

### CODE REVIEW

**Comment by satwikkansal** [comment]
@SaptakS Sorry, updated it :smile:

**Comment by SaptakS** [comment]
Please resolve merge conflicts.

**Comment by shubham-padia** [comment]
@satwikkansal You forgot to add the relevant migration files for the model changes. I've fixed that in #2925 . Please take care of that in future :)

**Comment by niranjan94** [comment]
@shubham-padia thanks for adding the missing migration file. But please don't mix it up with unrelated PRs. Create a separate PR for that. Because now, we have this PR (#2891) merged without the required migrations and the PR (#2925) with the migrations is still pending review.

**Comment by shubham-padia** [comment]
@niranjan94 Done.Have a look at #2931

**Comment by niranjan94** [comment]
@shubham-padia thanks a lot :)

**Pull request merged**
