### PR TITLE
Added the SETUP.md file for setting up Open Event Orga Server on mac

### PR DESCRIPTION
**Pull request by 1Niels**
No other changes were made besides the creation of the SETUP.md file.

### CODE REVIEW

**Comment by creativepsyco** [comment]
Squash commits please. We need only 1 commit per fix.

**Comment by 1Niels** [comment]
Sure! Is there anyway to do it online? I currently do not have access to terminal

**Comment by creativepsyco** [comment]
nope you need a terminal for it. https://yangsu.github.io/pull-request-tutorial/

**Comment by 1Niels** [comment]
Thanks for the help! I'll squash the commits as soon as I can.

**Comment by 1Niels** [comment]
https://github.com/fossasia/open-event-orga-server/pull/148

to make it simpler with the new commits to the repository

**Pull request closed without merging**
