### PR TITLE
Created Edit Event wizard

### PR DESCRIPTION
**Pull request by aditya1702**
step1
edit_step2
edit_step3
edit_step4

### CODE REVIEW

**Comment by aditya1702** [comment]
@rafalkowalski @SaptakS Please review. And the button 'Edit Event' in general-info has to be styled. @SaptakS could you please do it.
edit_event

**Comment by SaptakS** [comment]
@aditya1702 I think the styling is OK for the time. But if everyone thinks that the styling needs to be changed then we can work on it.

**Comment by aditya1702** [comment]
@SaptakS by styling I meant the fact that the 'Event Social Links' is not visible properly. Could you make it visible. :sweat_smile:

**Comment by rafalkowalski** [comment]
@aditya1702 please include a screen

**Comment by aditya1702** [comment]
edit3

**Comment by rafalkowalski** [comment]
@aditya1702 what about session types, tracks and social?

**Comment by aditya1702** [comment]
@rafalkowalski Sorry forgot to include them. Here included in the description :smile:

**Comment by rafalkowalski** [comment]
@aditya1702 add also with more options like twice social accounts

**Comment by aditya1702** [comment]
@rafalkowalski @SaptakS Done!

**Comment by rafalkowalski** [comment]
@aditya1702 great!

**Pull request merged**
