### PR TITLE
Post and PUT API input validation

### LINKED ISSUE #460: POST API | Add input validation
Currently there is almost no input validation in the POST API . 
For string and integer fields, we can use the min and max length params in flask-restplus.
And for more complex fields (like email and url), we can use custom fields to do the validation.
See #474

@shivamMg views ??

### PR DESCRIPTION
**Pull request by aviaryan**
Fixes #460 and #663 

This PR adds payload validation to datetime, email, color, url etc fields in the API. Other field types like strings, integers and float are automatically taken care by restplus.

@shivamMg @juslee @rafalkowalski  please review

### CODE REVIEW

**Comment by aditya1702** [comment]
@aviaryan I have made changes to the database..added new columns due to which the API tests are failing .Could you check them?

**Comment by aviaryan** [comment]
@aditya1702 Link ? which PR ?

**Comment by aditya1702** [comment]
@aviaryan #560

**Comment by aviaryan** [comment]
Adding PUT API input validation

**Comment by aviaryan** [comment]
@shivamMg please review.

**Comment by shivamMg** [comment]
@aviaryan Done :+1:

**Pull request merged**
