### PR TITLE
i18n and translation update

### LINKED ISSUE #2621: Language Box on Footer behaves improperly
The language box on the Footer doesn't shows any language selected by default and this is something not suitable in my eyes as far as UX is concerned. 
When I click on the dropdown/dropup box on my device (case iPad) I Can find English, while English is already default on site (but not default on the box).
img_1432
img_1433

Also when I select other language (German) only few parts on the navigation section is translated to German, while many parts remain non-translated.

img_1434

Is this default language issue for the box at Footer only on small devices? I guess no, it could also be for PCs. #GCI16

Thanks.

### PR DESCRIPTION
**Pull request by niranjan94**
- Resolves #2621
- Added machine translated Polish (#2577)
- Added machine translated Indonesian (#2574)
- Updated existing German translations

### CODE REVIEW

**Comment by niranjan94** [comment]
@mariobehling @SaptakS please review and merge

**Comment by jayvdb** [comment]
In future, please do not add machine translations, unless you mark them as fuzzy in the `.po`, and even then it is a reallllly bad idea.

**Comment by niranjan94** [comment]
I did mark them as fuzzy ... 

But I'll keep that in mind thanks :smile:

**Comment by niranjan94** [comment]
@jayvdb yep. you make sense. I'll revert the machine translated entries.

**Comment by jayvdb** [comment]
> I did mark them as fuzzy ...
> But I'll keep that in mind thanks 😄

https://github.com/fossasia/open-event-orga-server/commit/0077c65d18 says you didnt mark them as fuzzy.
And [100% translated Indonesian](https://hosted.weblate.org/translate/open-event/organizer-server/id/) with none marked for review means translators dont know where to start, and dont know what has been reviewed, and what is left to do.

**Pull request merged**
