### PR TITLE
Add Access code API, Docs and Dredd test

### LINKED ISSUE #3985: Implement Access Code API with relationship and permissions
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Access Code API missing

- Implement access_code API
- add access_code API to api doc and dredd testing

### PR DESCRIPTION
**Pull request by enigmaeth**
Fixes #3985.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

- Add AccessCode API
- Add docs for the Access Code API
- Add dredd tests for Access Code API docs

### CODE REVIEW

**Comment by enigmaeth** [comment]
@niranjan94 Just to confirm, each ticket can have only one access code, right?

**Comment by shubham-padia** [comment]
@enigmaeth Yes

**Comment by niranjan94** [comment]
@enigmaeth @shubham-padia no. Not at all. 

Each ticket can have multiple access codes. A single access code can be for multiple tickets. I forgot how the implementation is in vintage. But, this is what we want.

**Comment by enigmaeth** [comment]
@niranjan94 @shubham-padia @SaptakS  Added tickets with many-to-many relationship. Please review now. 
Thanks!

**Comment by enigmaeth** [comment]
@niranjan94 @shubham-padia  Please review.

**Comment by shubham-padia** [comment]
> Previously the db field used was tickets. Can be deleted now.

@enigmaeth This and  adding the relationship in the models itself also is still remaining

**Comment by enigmaeth** [comment]
@shubham-padia @niranjan94 Please review again. (Previous review was dismissed!)

**Comment by enigmaeth** [comment]
@niranjan94 @shubham-padia @SaptakS Could you please review this now?

**Comment by enigmaeth** [comment]
@SaptakS @niranjan94 @shubham-padia Could you please review this now? 
(Multiple heads issue resolved)

**Comment by enigmaeth** [comment]
@niranjan94 Please review this :sweat_smile: !

**Pull request merged**
