### PR TITLE
Added box shadow class for uniform look and ability to search a given event for a speaker

### PR DESCRIPTION
**Pull request by codethejason**
Added "well" class for box shadow in Sponsor/Speaker/Track/Microlocation templates and also in the listing events template (with 4 space indentations). Also second commit solves #146.

### CODE REVIEW

**Comment by leto** [comment]
@codethejason could you create a new PR without the second commit? That was already completed in #153 . Thanks

**Comment by codethejason** [comment]
@leto Done, but could you remove all the duplicate tasks in Code-in? It's a little confusing and counter-productive to have tasks that are already completed.

**Comment by codethejason** [comment]
@leto Also could you make this task available again: https://codein.withgoogle.com/tasks/6658844751036416/?

I need to submit this PR but it won't let me claim the task.

**Comment by leto** [comment]
@codethejason I agree with you. Someone outside GCI completed the tasks and I don't have the ability to remove them. I have already asked @mariobehling to remove them

**Comment by codethejason** [comment]
@leto Alright, do you have the ability to modify https://codein.withgoogle.com/tasks/6658844751036416/ so that I can claim it?

**Comment by leto** [comment]
Thanks @codethejason, looks good!

**Pull request merged**
