### PR TITLE
Send email to ticket purchaser on cancelling ticket

### LINKED ISSUE #4281: Send Email on cancelling ticket
Parent #4196 
An email sent to the purchaser when a ticket is canceled.

### PR DESCRIPTION
**Pull request by poush**
Fixes #4281

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by poush** [comment]
@niranjan94 @SaptakS can you please tell me what has to be sent for "cancel_note" and "order_url".

**Comment by SaptakS** [comment]
@poush order_url is simply the url of the order to which the ticket belongs. Cancel note I think on pressing cancel, you are supposed to enter a message on why you are cancelling. @niranjan94 can confirm though.

**Comment by poush** [comment]
@niranjan94 confirm please

**Comment by shubham-padia** [comment]
afaik @SaptakS is right, @poush please proceed.

**Pull request merged**
