### PR TITLE
Created template for Admin Trash

### PR DESCRIPTION
**Pull request by aditya1702**
trash1
trash2
trash3
#1220

### CODE REVIEW

**Comment by aditya1702** [comment]
@mariobehling Please review

**Comment by mariobehling** [comment]
@aditya1702 This is a good first step, but deleted items should not be a separate top menu tab. For example "Deleted Events" should have their tab in http://open-event.herokuapp.com/admin/events/ behind the "Past" tab and before the "Import" tab. Same for the others. Please add them into the right tab menus.

screenshot from 2016-06-27 00 14 04

**Comment by mariobehling** [comment]
@aditya1702 I had to revert your PR. You have changed the style of the menu bar and you have changed the location of the number of sessions dropdown menu and the search bar. Please stick to the design as is.

**Comment by mariobehling** [comment]
I just wish you could put a little more attention to detail. Thanks.

**Comment by aditya1702** [comment]
@mariobehling Sorry. I was still working on it. I will add a [Do not Merge] title to it till it is ready

**Pull request merged**
