### PR TITLE
Remove creator from event model

### LINKED ISSUE #3184: Remove redundant creator fields from event model
Remove redundant creator fields from event model. It was used before user event roles were implemented

### PR DESCRIPTION
**Pull request by shubham-padia**
fixes #3184 .
selection_127

### CODE REVIEW

**Comment by niranjan94** [comment]
@shubham-padia remove creator completely. It was used before we had user event roles.

**Comment by shubham-padia** [comment]
@niranjan94 I'm afk right now, I'll do the changes on tuesday, if its ok :smile:

**Comment by niranjan94** [comment]
@shubham-padia not an issue :) No hurry

**Comment by shubham-padia** [comment]
@niranjan94 Please review again. If this seems okay, I think changes have to be made in open-event repo too.

**Comment by niranjan94** [comment]
@shubham-padia I'm afk right now. Will review it tomorrow morning.

**Comment by niranjan94** [comment]
@shubham-padia yes. Please make the required changes at https://github.com/fossasia/open-event too

**Pull request merged**
