### PR TITLE
Ticket start time according to event timezone

### LINKED ISSUE #2805: Event Ticket time start on local PC time instead of Time of Event location
After the user entered the ticket, the ticket time starting the sales is automatically chosen - as the current time.

The time displayed is the current ticket time of the time zone. If the timezone of the user/PC is different to the timezone of the event, the ticket time still shows the PC timezone.

Expected behavior: Show the timezone of the event and make all ticket sales according to the event timezone.

screenshot from 2016-12-31 22-19-44

### PR DESCRIPTION
**Pull request by shubham-padia**
Fixes #2805 .
Visit http://orga3.herokuapp.com/ for a demo.
Please review.

### CODE REVIEW

**Comment by mariobehling** [comment]
The commit also seems to change the event start time, which results in "invalid time range".

screenshot from 2017-01-01 23-52-08

**Comment by mariobehling** [comment]
Oh, it seems this bug also exists now on eventyay.com.

**Comment by mariobehling** [comment]
Does not solve the issue.

Also I see that the pre-filled ticket sales time starts at 11pm and ends at 10pm.

The preview states ticket sales "will" start, but the time has passed already.

screenshot from 2017-01-01 23-57-32

**Comment by shubham-padia** [comment]
The issue that you mentioned in the comment is a different issue #2806 which is yet to be solved. 
This pr solves #2805 according to which default start time for the event should be according to the event timezone

**Comment by shubham-padia** [comment]
You can change the event timezone -> add a new ticket -> view start time of the ticket sales which will be according to the event timezone

**Comment by mariobehling** [comment]
Event timezone is Berlin UTC +1. Sales shows "This ticket's sale will start on January 01, 2017 11:50 PM". Time is: January 2, 00:08. Ticket sales should be available, but they are not. Which time is the ticket sales using? The issue is that ticket sales are not available even though they should in the timezone defined.

**Comment by shubham-padia** [comment]
The issue that you are mentioning is #2806 . This PR does not fix that.
This PR only fixes #2805 .

**Comment by shubham-padia** [comment]
I think i'll close this for now and provide changes for both #2806 and #2805

**Comment by mariobehling** [comment]
Ok, I think both need to be fixed together. Thank you for taking care!

**Comment by shubham-padia** [comment]
No problem 😄

**Pull request closed without merging**
