### PR TITLE
Implemented Admin Trash

### PR DESCRIPTION
**Pull request by aditya1702**
#1220 
trash1
trash2
trash3

For the normal user the item deleted will not be shown in the tables. However it wont be deleted from the database.
trash4
trash5

Each item has a property in_trash which will be set to True as soon as the user deletes the item(session, event, user). And it will be shown in the trash of the admin.
trash6
trash7
trash8

However once it is deleted from the trash it will be permanently deleted from the database and a message will flash "Your item has been permanently deleted"
trash12
trash10

### CODE REVIEW

**Comment by aditya1702** [comment]
@mariobehling I think this is how you wanted the top bar to look. The trash feature is working. Just the "30 days" time slot is to be implemented. I will make that commit as soon as possible :)

**Comment by aditya1702** [comment]
@mariobehling Please review

**Comment by mariobehling** [comment]
@aditya1702 The screenshot below "However once it is deleted from the trash it will be permanently deleted from the database and a message will flash "Your item has been permanently deleted" is the wrong location in the "user space". This message should appear in the admin space. Please check.

**Comment by mariobehling** [comment]
Ok, let's test this on the system. Please also test this in detail on the live system and write tests. Thank you.

**Pull request merged**
