### PR TITLE
Implement Payment system

### PR DESCRIPTION
**Pull request by aditya1702**
#1848 
If type is 'Paid' or 'Donation' then payment options will be displayed:

If country is United States and US dollars then no PayPal options. But if any other country then PayPal option will be available

### CODE REVIEW

**Comment by aditya1702** [comment]
@mariobehling @niranjan94 Please review. It is still incomplete. I have to add tax options and fee options outlined by https://github.com/fossasia/open-event-orga-server/issues/1920

**Comment by mariobehling** [comment]
> If country is United States and US dollars then no PayPal options. But if any other country then PayPal option will be available

What is the logic behind this? Just follow what other services do. You always need an email for paypal services where-ever you are, also in the US.

**Comment by aditya1702** [comment]
@mariobehling I did not think of this logic. Eventbrite displays it like this only. I saw it on Eventbrite hence I added it

**Comment by mariobehling** [comment]
I cannot see you whole screen, but I see that you need to enter a paypal email at least once even on your screenshots.

**Comment by mariobehling** [comment]
Maybe Eventbrite has different payment options within the US, but we do not.

We need it as below.

screenshot from 2016-07-28 18 12 40

**Comment by aditya1702** [comment]
@mariobehling Please review if its proper

**Comment by aditya1702** [comment]
@mariobehling Please check

**Comment by aditya1702** [comment]
@mariobehling @shivamMg @niranjan94 Please review and merge

**Comment by niranjan94** [comment]
Could you modify the existing tests or add some new tests so that all the new form fields are included ? 0.3% coverage decrease seems to be a bit on the higher side. And I think we need proper tests for ticketing/payment related items from the start.

**Comment by niranjan94** [comment]
@aditya1702 please resolve the conflicts

**Comment by niranjan94** [comment]
@aditya1702 Where is this displayed ? I can't seem to find it on the Event Creation Wizard.

**Comment by aditya1702** [comment]
@niranjan94 Enable the ticketing and payment switches on the modules page. It will be displayed then

**Comment by niranjan94** [comment]
See https://open-event-dev.herokuapp.com/admin/modules/ .. All the switches are enabled.

**Comment by niranjan94** [comment]
@aditya1702 ?

**Pull request merged**
