### PR TITLE
Form Validation in Event Wizard corrected

### LINKED ISSUE #1461: Make floor for rooms compulsory
Floors for rooms need to be compulsory. For now, it gives internal error. Will be adding form validation.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixed #1461 #1462 

@mariobehling @rafalkowalski please review

### CODE REVIEW

**Comment by rafalkowalski** [comment]
@SaptakS do we need fllor field as required?

**Comment by SaptakS** [comment]
Yes.. That is how the DB schema is right now.. Else it gives an internal error..

**Comment by rafalkowalski** [comment]
@SaptakS @mariobehling i think floor field can't be required, we need to create event in short time, we don't need to wonder which floor we should put. So in database this field is wrong implemented

**Comment by SaptakS** [comment]
@rafalkowalski For creating an event, floor field is not required.. It is required only when you create a microlocation.

**Comment by rafalkowalski** [comment]
@SaptakS ok

**Pull request merged**
