### PR TITLE
Fixed the IO error

### LINKED ISSUE #4468: IOError: cannot identify image file <cStringIO.StringI object at 0x7fc26db50a48>
https://sentry.eventyay.com/eventyay/dev-api/issues/49/

```
IOError: cannot identify image file <cStringIO.StringI object at 0x7fc26db50a48>
(15 additional frame(s) were not displayed)
...
  File "app/api/helpers/permissions.py", line 43, in decorator
    return fn(*args, **kwargs)
  File "app/api/helpers/permission_manager.py", line 58, in is_coorganizer
    return view(*view_args, **view_kwargs)
  File "app/api/events.py", line 322, in before_update_object
    uploaded_images = create_save_image_sizes(data['original_image_url'], 'event', event.id)
  File "app/api/helpers/files.py", line 156, in create_save_image_sizes
    'original_image_url': create_save_resized_image(image_file, 0, 0, 0, original_upload_path, resize=False),
  File "app/api/helpers/files.py", line 77, in create_save_resized_image
    im = Image.open(image_file)

IOError: cannot identify image file <cStringIO.StringI object at 0x7fc26db50a48>
```

### PR DESCRIPTION
**Pull request by invinciblycool**
Fixes #4468 

#### Short description of what this resolves:
Resolves the IO error.

### CODE REVIEW

**Comment by shubham-padia** [comment]
I think some exception handling may also be needed here, if the image is invalid. Please provide exception handling accordingly, try with a corrupted/invalid image

**Comment by invinciblycool** [comment]
Sure. Busy with exams.
Will add an exception handling statement ASAP.

**Comment by invinciblycool** [comment]
@shubham-padia Added exception handling.

**Comment by shubham-padia** [comment]
Thanks :). The tests are failing rn, please look into that. You can find the error info in travis logs

**Comment by invinciblycool** [comment]
I have checked through the logs but couldn't relate my commit with the error. I guess the error is not because of the commit.What should I do?

**Comment by invinciblycool** [comment]
@shubham-padia The checks are passing now :+1:

**Pull request merged**
