### PR TITLE
Comments field converted to textarea

### PR DESCRIPTION
**Pull request by SaptakS**
#990 

> Make comments into a paragraph.

screenshot from 2016-06-20 13 51 01

### CODE REVIEW

**Comment by SaptakS** [comment]
@mariobehling fixes last point of #990

**Comment by SaptakS** [comment]
The build error is not due to this PR. I will check it out though.

**Comment by niranjan94** [comment]
@SaptakS this error has been fixed in my prev. PR

**Comment by SaptakS** [comment]
@niranjan94 saw that. I have merged that PR.

**Pull request merged**
