### PR TITLE
Internal server error due to I18N marked strings resolved

### PR DESCRIPTION
**Pull request by sainiak009**
There were some strings marked wrongly. Corrected them now.

### CODE REVIEW

**Comment by niranjan94** [comment]
@sainiak009 there seem to be conflicts. and some old commits are also here. Could you clean up ?

**Comment by sainiak009** [comment]
@niranjan94 Please check gitter I have some queries.

**Comment by niranjan94** [comment]
@sainiak009 there are still old commits here. I think a fresh PR from a fresh up-to-date branch would be better.

**Comment by sainiak009** [comment]
@niranjan94 Okay creating a fresh PR for this.

**Pull request closed without merging**
