### PR TITLE
Tickets/Multiple Tickets feature

### PR DESCRIPTION
**Pull request by shivamMg**
https://github.com/fossasia/open-event-orga-server/issues/1862

@mariobehling @niranjan94 Please review and merge.

screenshot from 2016-07-30 14 48 46

**Update:** Solved Datepicker & Timepicker bug (https://github.com/fossasia/open-event-orga-server/issues/1980). Added smooth transitions and better UI.

screenshot from 2016-08-01 11 13 39

### CODE REVIEW

**Comment by shivamMg** [comment]
@mariobehling @niranjan94 Please review and merge.

**Comment by niranjan94** [comment]
@shivamMg Could you modify the existing tests or add some new tests so that all the new form fields are included ? 0.3% coverage decrease seems to be a bit on the higher side. And I think we need proper tests for ticketing/payment related items from the start.

**Comment by shivamMg** [comment]
@niranjan94 The API POST data test samples don't include tickets so I've added them with `data` inside tests. Please review and merge.

**Comment by niranjan94** [comment]
Multiple tickets are already displayed at /e/event_id/ when the ticketing module is enabled. But direct check on the database should do for now.

**Comment by shivamMg** [comment]
@niranjan94 Linting issues solved, please review.

**Pull request merged**
