### PR TITLE
Rejected Session label from in red #3225

### LINKED ISSUE #3225: Sessions Dashboard: Show rejected sessions in red
Rejected sessions currently have the same orange background color as pending sessions. Please change the background color of rejected sessions to red.

screenshot from 2017-02-20 17-41-23

### PR DESCRIPTION
**Pull request by Himanshi-Khandelwal**
Color change of rejected session label to red.

Please review.

### CODE REVIEW

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 earlier it was given like this , that's why I didn't changed that. I 'll change this .

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 done the changes . 
screenshot from 2017-02-23 09 51 32

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 till here I have done for squash , where HEAD~2 for the last two commits.
now git push -f origin branch?
screenshot from 2017-02-23 10 41 55

**Comment by aviaryan** [comment]
@Himanshi-Khandelwal 
You can use `git log` to check if the commits were correctly squashed. Alternatively, you can use a GUI git client like SmartGit for better visualisation of git history and diffs. Once you are convinced that everything is good, you can go with the force push.

**Comment by Himanshi-Khandelwal** [comment]
@aviaryan in git log I am seeing commits done by others also and my 2 commits are converted to 1
screenshot from 2017-02-23 11 06 17

**Comment by aviaryan** [comment]
Great. So for being sure, just run `git show {commitHash}` to see if all changes were included in your squashed commit. After that, you can force push.

**Comment by Himanshi-Khandelwal** [comment]
thanks a lot @aviaryan all done !!!!!

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal always, please give a proper commit message (http://chris.beams.io/posts/git-commit)

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 I will keep this in mind.

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal thank you :) ... So, please change the commit message here to something more meaningful

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 done .... hope this OK.  :)

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal I meant the commit message. not the PR title ...

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 I think this one will work ...................

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal no. PR title is different from commit message. You can change the commit message by the amend function
`git commit --amend` then force push to this branch.

**Comment by Himanshi-Khandelwal** [comment]
commit message written . by using git commit --amend

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal `Fixed issue #3225` is not a meaningful commit message. Tell what has been done in a short and sweet manner. Please see https://chris.beams.io/posts/git-commit/ and read through that entire article. It's so clear ... 

Also, I urge you to read the [**Contributions Best Practices**](https://github.com/fossasia/open-event-orga-server#contributions-best-practices) section of this project's [readme](https://github.com/fossasia/open-event-orga-server#contributions-best-practices).

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94  now check https://github.com/fossasia/open-event-orga-server/pull/3233/commits/6e00836dbec8c214aba60c8a2a0963a45592f8f1

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal the commit needs to be easy to understand and readable at a glance.. Nobody is gonna open a comment and read... See commit messages of @shubham-padia for example... Follow his lead

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal I think you misunderstood the article.. The first line of the commit should be short. Easy and quick to read and to the point. Such a long essay-like explanation is not required for this simple change. Explanations may be necessary only your commits do a lot of complex changes

Maybe some thing like `Change color of rejected session label to red`. It's straightforward. To the point. Tell exactly what was done. Easy to ready. Don't you agree? :)

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 done

**Pull request merged**
