### PR TITLE
Contact info submitted using email id only #3386

### PR DESCRIPTION
**Pull request by Himanshi-Khandelwal**
Adding phone no. not compulsory in contact info.

### CODE REVIEW

**Comment by Himanshi-Khandelwal** [comment]
done

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal 

Make sure your commit messages says what exactly was done in a commit. No need to put issue number in the commit. We have a PR for that.

Add issue number in PR like this https://github.com/blog/1506-closing-issues-via-pull-requests .

For a good commit message, see the below examples,

Fixes Issue #38 - Doesn't say anything :x:
Two alert dialogs issue solved - Says what was fixed. But not what change has been done in the commit :x:
Unsubscribe network change listener on disconnect and re-subscribe - Tells the exact change that was done in that commit :white_check_mark:

**Comment by Himanshi-Khandelwal** [comment]
thanks @niranjan94 hope this is ok now!!

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal I think you mis-understood `Contact info submitted using email id only` doesn't say what code change was done. It says what is the result of the code change ... 

A more appropriate commit message would be `make email field optional in contact info`

**Pull request merged**
