### PR TITLE
CSS styles for schedule printing

### PR DESCRIPTION
**Pull request by rctay**
vis-a-vis #3335. We generate  a bootstrap that does not clear print styles (print.less), as it was clearing things like horizontal rules in the schedule timeline.

Preview: [FOSSASIA Summit - eventyay.pdf](https://github.com/fossasia/open-event-orga-server/files/888452/FOSSASIA.Summit.-.eventyay.pdf)

### CODE REVIEW

**Comment by rctay** [comment]
Excluding generated bootstrap.

**Comment by rctay** [comment]
Oops, forgot to amend commit message. Done.

**Comment by SaptakS** [comment]
@rctay can you please explain what you are trying to do and how this is going to help in getting print out of schedule?

**Comment by rctay** [comment]
I am trying to get print per #3335, but some styles which are useful in the printout like the horizontal bars are getting cleared out by bootstrap's "clear print" rules. I have experimented with adding them back by hand but there are far too many styles getting cleared so it becomes a hodgepodge of `!important` rules. You can have a look at the approach I am taking in https://github.com/rctay/open-event-orga-server/tree/guest-schedule-print .

Hence I am generating a bootstrap css without "clear print" rules, which bootstrap includes by default via the `@import "print.less"`.

**Comment by mariobehling** [comment]
@rctay @niranjan94 Should we merge this and iterate from here? It is already an improvement.

**Comment by rctay** [comment]
Updated to fix a merge conflict due to activity on `development` branch.

**Pull request closed without merging**
