### PR TITLE
Discount codes: Include fees in discount and show discount for individual tickets

### LINKED ISSUE #2863: Implement "Apply" Promotional Code on event site itself
Our promotional code/discount gets applied only after the user advances to the next page.

Expected: 
* [x] There should be an "Apply" button on the right hand side of the promotion field (when it is expanded).
screenshot from 2017-01-07 19-33-17

* [ ] After the user hits "Apply":
    * [ ] Display below the ticket type the applied discount, e.g. Discounted 50%
    * [ ] Display the new (discounted) ticket price in the price column and the old ticket price crossed

Compare:

screenshot from 2017-01-07 19-41-23

### PR DESCRIPTION
**Pull request by shubham-padia**
fixes #2863 .
partially solves #3007 .

For discount code logic:
selection_092

For #2863.
selection_094

### CODE REVIEW

**Comment by shubham-padia** [comment]
@SaptakS 
AFAIK The screenshot in the issue showed strike through on the total, but showing it on individual tickets seems even a better idea !! @mariobehling @hpdang @niranjan94 comments ??

**Comment by SaptakS** [comment]
@shubham-padia please check the issue carefully the main description part. It clearly states for a particular ticket type. Not total.

> Display the new (discounted) ticket price in the price column and the old ticket price crossed

**Comment by shubham-padia** [comment]
@SaptakS Thanks for the clarification !! Misunderstood the screenshot apparently.

**Comment by shubham-padia** [comment]
@SaptakS Did the required changes. Any suggestions to this ?
selection_087

**Comment by mariobehling** [comment]
Thanks. But: If the ticket discount is 100% and the ticket costs 0.00 then the fee is calculated from 0.00 as well and should be 0.00 as well. Could you showcase that with a more usual discount of e.g. 20%, please?

**Comment by shubham-padia** [comment]
> If the ticket discount is 100% and the ticket costs 0.00 then the fee is calculated from 0.00 as well and should be 0.00 as well

Yeah, just noticed this, it is an error in the discount code logic (screenshot below), currently fees are excluded from discount.

selection_089



Requested screenshot for 20% discount:
selection_088

**Comment by shubham-padia** [comment]
@mariobehling @SaptakS  This PR also fixes #3007 now :)

**Comment by shubham-padia** [comment]
Buy some tickets at https://orga3.herokuapp.com/e/64a65ca2/ :wink: , for testing purposes. Discount code is `free` for 100% discount. Cheers.

**Comment by mariobehling** [comment]
After applying the discount, please also show the fee as "0.00" (no need for crossed through fee, just change the display from 0.40 to 0.00 in this case)

**Comment by mariobehling** [comment]
The fee display should also have the usual way currencies are displayed: e.g. US$ 0.40 instead of US$ 0.4

**Comment by shubham-padia** [comment]
@mariobehling @SaptakS done. Please check again on http://orga3.herokuapp.com/e/64a65ca2/ .

**Comment by SaptakS** [comment]
@shubham-padia please do this as well https://github.com/fossasia/open-event-orga-server/issues/3007#issuecomment-274242217. Thanks.

**Comment by shubham-padia** [comment]
@SaptakS fees have not been implemented on the dashboard at all. So that needs to be fixed, which is out of scope of this PR. Please look into that. Cheers.

**Comment by SaptakS** [comment]
@mariobehling please check the screenshots... If you feel it is good to be merged, then it's cool.

**Comment by mariobehling** [comment]
Good job! Thank you.

**Comment by mariobehling** [comment]
@SaptakS This needs to go live as quickly as possible. @hpdang Is asking me every minute about it. Thanks!

**Pull request merged**
