### PR TITLE
Changed Color picker in event creation

### PR DESCRIPTION
**Pull request by aditya1702**
https://github.com/fossasia/open-event-orga-server/issues/433

### CODE REVIEW

**Comment by aditya1702** [comment]
@rafalkowalski Done

**Comment by SaptakS** [comment]
Seems good to be merged.

**Comment by aditya1702** [comment]
@SaptakS @rafalkowalski I am not able to add color picking property to the new added elemenst, so I am openeing up an issue regarding it. This can be merged and someone can fix it :smile:

**Comment by rafalkowalski** [comment]
@aditya1702 please open ticket

**Comment by SaptakS** [comment]
https://github.com/fossasia/open-event-orga-server/pull/453 Fixes new element problem.

**Pull request merged**
