### PR TITLE
add absorb fees/pass on fees to tickets

### LINKED ISSUE #2894: Add absorb or pass on fees to the ticketing system
Open Event has a fee system, that can be defined in the admin section. See screenshot:

screenshot from 2017-01-09 21-17-01

Please implement "absorb fee" or "pass on fees" in the ticketing system similar to other systems.

screenshot from 2017-01-09 21-11-55

If fees are absorbed, do not show them in the ticketing sales as described here: https://github.com/fossasia/open-event-orga-server/issues/2851

### LINKED ISSUE #2924: Ticketing: Implement logic for fees defined in the settings section
Fees defined in `admin/settings` have not been implemented in the ticketing logic. Implement this along with `absorb fees` from #2894 .
P.S working on this.

### PR DESCRIPTION
**Pull request by shubham-padia**
fixes #2894.
fixes #2924 .

selection_065

selection_066

selection_067

### CODE REVIEW

**Comment by SaptakS** [comment]
Please squash the commits. I feel these 3 commits shouldn't be separate. Thanks.

**Comment by SaptakS** [comment]
Also please make a commit for the backend in this pull request only... Only frontend doesn't make any sense in my opinion.

**Comment by shubham-padia** [comment]
@SaptakS Thanks. I'll resolve #2924 in this PR only :+1: , was just trying to follow 1 PR -> 1 issue which I personally find convenient to work with :smile: .

**Comment by mariobehling** [comment]
> was just trying to follow 1 PR -> 1 issue which I personally find convenient to work with

Absolutely. Thank you.

@SaptakS But, let's then only merge when the backend has been implemented. So, we don't get people who will file a bug report as this feature is still under development.

@shubham-padia Please make the PR for the backend when you are ready and we merge each of the PRs then. Looks good to me. Cheers.

**Comment by SaptakS** [comment]
@mariobehling sounds good to me. That was my point that people might start thinking it as bug without backend.

**Comment by SaptakS** [comment]
@shubham-padia please resolve codacy issues.

**Comment by shubham-padia** [comment]
@SaptakS Implemented the logic and thus fixed #2924 . All of the commit seem logical to me. Please review again. Thanks.

**Comment by shubham-padia** [comment]
@SaptakS Ready to merge :)

**Pull request merged**
