### PR TITLE
[WIP]Fixing api blueprint to remove dredd parse warnings

### LINKED ISSUE #4519: Fix api-blueprint parse warnings
Following is a snapshot of the warnings by the apib parser when dredd is being run: https://pastebin.com/ckP4XtjZ. For the latest data, you can run the dredd tests locally or have a look at the travis build logs for the project

### PR DESCRIPTION
**Pull request by invinciblycool**
Fixes #4519 

#### Short description of what this resolves:
Resolves some of the parse warnings from dredd.
Still [these](http://paste.ubuntu.com/25830472/) warnings persist as some of these warnings have been known issues in dredd itself.
@shubham-padia If you could guide as to how to suppress or fix those warnings.

#### Changes proposed in this pull request:

- Edits in the `api_blueprint_.apib`

### CODE REVIEW

**Comment by shubham-padia** [comment]
@invinciblycool you would have to add `+ Parameters` on line 9482 i.e https://github.com/fossasia/open-event-orga-server/blob/8c1f379f691c7247c217572d3e53c299bd798045/docs/api/api_blueprint.apib#L9482
and one of the recognized block errors on line 20000 is due to the blank line. You can figure out the rest of the errors after this I think ;)

**Comment by invinciblycool** [comment]
@shubham-padia  I had already tried adding `Parameters` to `task_id` but it still was showing a error(You can check the logs).I also tried for invoice but still the error persists.
The blank line although solved the problem. Will commit with the complete solution.

**Comment by invinciblycool** [comment]
@shubham-padia How should I proceed now?

**Comment by poush** [comment]
@invinciblycool Try using Apiary.io you can easily debug and solve errors from it.

**Comment by invinciblycool** [comment]
@poush I will try that and update...
Thanks.

**Comment by invinciblycool** [comment]
@poush @shubham-padia Sorry for the delay. Apiary was not of much help. In the end it was just a white-space missing which was causing the problem :sweat_smile:

**Comment by shubham-padia** [comment]
@invinciblycool I'm squashing and merging for now, but please squash your commits if they have a similar message :smile:

**Comment by invinciblycool** [comment]
Sure. Will keep this in mind. Thanks .

**Pull request merged**
