### PR TITLE
Username with avatar shown

### PR DESCRIPTION
**Pull request by SaptakS**
#360

### CODE REVIEW

**Comment by juslee** [comment]
@SaptakS Implement gravatar for the user.

**Comment by SaptakS** [comment]
@juslee I am on it..

**Comment by juslee** [comment]
@SaptakS fall back to the default photo. If the person is logged in using google/facebook/twitter, use the image from that profile.

**Comment by SaptakS** [comment]
@juslee this is in the gsoc branch.. So, the login with gmail/facebook authentication isn't added in this code.. Once thats done, I will make the necessary modifications.. For now I have added a field to provide a link for profile pic. If that is available, we show that, otherwise default.

**Pull request merged**
