### PR TITLE
Refactor: Migrate timestamp fields to timestamp_tz w/ proper tz

### LINKED ISSUE #3739: Migrate all data in datetime fields to `time-stamp with timezone`
Currently all of the datetime fields store time as a timestamp without timezone. Migrate all data in datetime fields to `time-stamp with timezone` according to the timezone field.

- We should first start storing date time with proper timezone in the db itself. Right now, all our date time fields are of the data type timestamp without time zone. Needs to be changed to timestamp with time zone.
- The timezone db column in the events table is only for storing the name of the timezone. (since different names can have the same UTC offset). The actual offset information should be taken from and used from the date time fields.
- This applies to all tables and all date time fields. events, sessions, tickets, and everything else. Included created at and deleted at. For internal fields (like created at and deleted at), we should use utc. This is important because the frontend will be localising all dates and times based on user's preferences. Included deleted at and created at.

### PR DESCRIPTION
**Pull request by shubham-padia**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Refactor: Migrate timestamp fields to timestamp_tz w/ proper tz

#### Changes proposed in this pull request:

- Take care of invalid timezone inputs with 'string'

Fixes #3739 

Note: start_date and end_date in call_for_papers have a wrong name, I'll change them when solving #3759, I want to keep this a seperate commit

### CODE REVIEW

**Comment by shubham-padia** [comment]
A date with timezone 'utc' changes from `"2017-04-17 04:37:15.66815"`  to `2017-04-17 10:07:15.66815+05:30`, please check if this is right before merging

**Comment by shubham-padia** [comment]
Tests are failing at multiple places due to `TypeError`,
@niranjan94 What should be done.
should I modify the tests for now (it'll be fairly simple, but time-consuming), or should they be removed ? 
Currently they just make sure that the app runs fine, it also tests other functionality, but we are not using the helpers.

**Comment by niranjan94** [comment]
@shubham-padia remove those failing tests please.

**Comment by niranjan94** [comment]
> A date with timezone 'utc' changes from 2017-04-17 04:37:15.66815 to 2017-04-17 10:07:15.66815+05:30, please check if this is right before merging

Just to be sure ... Can you give an example with the timezone as `Asia/Kolkata` ?

**Comment by shubham-padia** [comment]
@niranjan94 With `Asia/Kolkata`, 
`"2016-12-31 16:30:00"` changes to `"2016-12-31 16:30:00+05:30"`

**Comment by niranjan94** [comment]
Looks good.

**Comment by shubham-padia** [comment]
@niranjan94 Tests are passing now. I've replaced the previous dates in tests with timezone aware dates, only those tests have been removed which had some `.localize` or some other date function burried deep into the code-chain

**Comment by shubham-padia** [comment]
Please review

**Comment by niranjan94** [comment]
@shubham-padia please resolve conflicts. Otherwise looks good.

**Comment by shubham-padia** [comment]
@niranjan94 conflicts resolved.

**Pull request merged**
