### PR TITLE
Added export and import event in UI

### LINKED ISSUE #780: Implement Import/Export buttons in event manager
Please implement Import and Export of Events as shown below in the Event Manager http://open-event.herokuapp.com/events/

The ultimate design will probably be different, but for the moment the following should be good:
* [ ] **Import Tab**, that opens an overlay box for the import
* [ ] An icon in the "Options Area" to **export** an event

screenshot from 2016-06-13 16 24 13

### PR DESCRIPTION
**Pull request by aviaryan**
Fixes #780 

<strike>
I am not sure how to implement import event **overlay** in the UI. 
Is there any overlay library we are using ? I looked through bower.json but don't think so. 
@niranjan94 @SaptakS Help needed.
</strike>

export_event_ui

import_event
import_error
import_success

### CODE REVIEW

**Comment by niranjan94** [comment]
@aviaryan what do you mean by overlay ? what do you want to do ?

**Comment by aviaryan** [comment]
@niranjan94 If I understand @mariobehling correctly, we need to show a popup that will have a browse button. The user will select event zip through it and then create on "Import Event". 
After that, the file will be POSTed to `api/v2/events/import/json` and on successful request, the response will have the newly created event. Then we will redirect to /event/{{new_event.id}} to show the newly created (imported) event. 
I don't know how to generate that popup here. Has the same been done in the project so that I can read the code and be consistent on how to do it ?

**Comment by niranjan94** [comment]
@aviaryan we already use bootstrap in this project. You could use a bootstrap modal. 
http://getbootstrap.com/javascript/#modals

**Comment by aviaryan** [comment]
@niranjan94 Thank you

**Comment by aviaryan** [comment]
@mariobehling @niranjan94 please review

**Pull request merged**
