### PR TITLE
Resoved issue #1598

### PR DESCRIPTION
**Pull request by sainiak009**
Added dropdown in place of buttons for responsive tabs on event details page.
I was interested in this issue, and discussed it too but again did the same mistake of not commenting here earlier. If possible please review my PR and merge it.

### CODE REVIEW

**Comment by niranjan94** [comment]
@sainiak009 please fix the tests

**Comment by SaptakS** [comment]
@sainiak009 I also feel the first 2 commits in this PR doesn't actually belong to this PR. Can you please look into it and squash the commits properly?

**Comment by sainiak009** [comment]
I have updated pull request with previous commits removed/stashed. Please review.

**Comment by sainiak009** [comment]
@niranjan94  Screenshots : 
screenshot 28
screenshot 29

**Comment by niranjan94** [comment]
@sainiak009 looks cool :) ... Good job !

**Pull request merged**
