### PR TITLE
Profile UI improved, Upload button added

### PR DESCRIPTION
**Pull request by SaptakS**
@aditya1702 @niranjan94 @mariobehling please review.
profile

### CODE REVIEW

**Comment by rafalkowalski** [comment]
@SaptakS are we going to add possibility to add a link?

**Comment by mariobehling** [comment]
@SaptakS Actually, the goal is to have people click on the profile image and they can set it, e.g. similar to Facebook or Twitter. Alternatively have an upload button below the profile image placeholder like Eventbrite.

screenshot from 2016-06-15 13 48 20

**Comment by mariobehling** [comment]
@SaptakS Where is the issue for this? Every PR needs to match an issue.

**Comment by mariobehling** [comment]
Closing this PR. Please create issue before. Actually, I do not see a substantial add of functionality in this PR neither.

**Pull request closed without merging**
