### PR TITLE
Page for Scheduler to comply with the URL Architecture

### LINKED ISSUE #696: Page for Scheduler
A separate page at `/events/ID/schedule/edit` as per #622 for the Scheduling tool.

### PR DESCRIPTION
**Pull request by niranjan94**
A separate page at /events/ID/scheduler as per #622 for the Scheduling tool. 

Resolves #696 . 

@SaptakS @rafalkowalski please review and merge.

### CODE REVIEW

**Comment by shivamMg** [comment]
The coverage is falling because `SchedulerView` doesn't have tests. You can write some tests with simple assertions if you like :smiley:, but the priority seems to be urgent so your discretion.

**Comment by niranjan94** [comment]
@shivamMg The Scheduler is a completely client side javascript-based tool. So, no tests right now. I'll add js tests once it's completed to an extent.

**Comment by shivamMg** [comment]
@niranjan94 I meant python unittests for `SchedulerView`.

**Comment by niranjan94** [comment]
@shivamMg I know you meant python unittests :smile: ... But, if you look into SchedulerView, you'll see that there's just one simple method that loads a template. 

I'll add unittests, python/js in one of the upcoming PRs.

**Comment by shivamMg** [comment]
@niranjan94 :+1:

**Pull request merged**
