### PR TITLE
add unit tests for validation functions in API

### LINKED ISSUE #4004: Add unit tests for validation functions of each schema
Add unit tests for validation functions of each schema

### PR DESCRIPTION
**Pull request by shubham-padia**
fixes #4004

### CODE REVIEW

**Comment by shubham-padia** [comment]
@niranjan94 @fossasia/open-event-server-devs Please review

**Comment by shubham-padia** [comment]
@SaptakS Can you please review again :) , had to make changes due to the latest DiscountCode merge

**Comment by SaptakS** [comment]
@shubham-padia please squash the two commits since I feel they don't exclusively serve different purposes? Correct me if I am wrong.

**Comment by shubham-padia** [comment]
@SaptakS Can you please squash and merge instead :wink:

**Pull request merged**
