### PR TITLE
Solved issue #3212. `Number of Sessions` in Event Dashboard in General Info Dashboard is Improved.

### PR DESCRIPTION
**Pull request by rahuldecoded**
Fixed issue #3212
0312357e-f5f9-11e6-8a36-6909e82a3b21

### CODE REVIEW

**Comment by rahuldecoded** [comment]
@niranjan94 Hey! I'm new to big projects, so I don't know to write a proper commit message, though is the commit message is okay now?

**Comment by niranjan94** [comment]
Hi @rahuldecoded you have changed the PR title. But your commit message is still unchanged. Use `git commit --amend` to change your message and then force push to your branch. 

See http://chris.beams.io/posts/git-commit/

**Comment by rahuldecoded** [comment]
Sorry something went wrong while working with git! I'm closing this PR again and sending a new PR.

**Comment by poush** [comment]
You don't need to close this PR, just amend the commit name and force push into your current branch. This PR will be updated automatically.

**Comment by niranjan94** [comment]
@rahuldecoded I agree with @poush . Please keep that in mind for any future PRs.

**Comment by rahuldecoded** [comment]
@niranjan94 @poush I'm sorry guys! I'll keep your advices in my mind. Thanks for helping. :D

**Pull request closed without merging**
