### PR TITLE
Fixes #3113: Adds from name to email

### LINKED ISSUE #3113: Specify from "Name" for emails in admin dashboard
The system emails that are sent out from eventyay currently show "info" as the name. Please implement a field in the email settings to specify a "Name" so when people get an email from the system this name shows up in their inbox.

screenshot from 2017-02-01 12-49-24

### PR DESCRIPTION
**Pull request by CosmicCoder96**
Fixes #3113 

Specifies from "Name" for emails in admin dashboard

image

### CODE REVIEW

**Comment by niranjan94** [comment]
And @CosmicCoder96 ... please comment on the issue _before_ you start working on it so that we can ensure multiple people are not working on the same issue

**Comment by CosmicCoder96** [comment]
@niranjan94
Thanks for the review. I will be sure to keep that in mind. 
I have now placed the from name text field on the upper part of the form to make it common to both. And since the payload in helpers.py is common to both smtp and sendgrid, I believe this should suffice. Please review again.

**Comment by niranjan94** [comment]
@CosmicCoder96 no. this would fail for sendgrid. Sendgrid expects only an email ID in the `from` field. For sendgrid you'd need to put the name in the `fromname` field. 

Please see https://sendgrid.com/docs/API_Reference/Web_API/mail.html

**Comment by niranjan94** [comment]
When using a third-party API/sdk, never assume a behavior. Always check the appropriate documentation and confirm.

**Comment by CosmicCoder96** [comment]
@niranjan94
Thanks for the advice. I have made the necessary changes.

**Pull request merged**
