### PR TITLE
Missing comma error in  static.py 

### LINKED ISSUE #3268: Missing comma error in  static.py

### PR DESCRIPTION
**Pull request by dristybutola**
Closes #3268

### CODE REVIEW

**Comment by niranjan94** [comment]
@dristybutola which issue is this PR linked to ?

**Comment by dristybutola** [comment]
@niranjan94  I just found 'this' while going through the code base in development branch , so no 
issue created i guess.

**Comment by niranjan94** [comment]
@dristybutola however small the issue maybe ... Even if it's a small indentation mistake, we need an issue linked to every PR ... Please create an issue and link it here

**Comment by dristybutola** [comment]
@niranjan94   Done!!

**Pull request merged**
