### PR TITLE
Aspect ratio, Profile Info and Logo Info added

### PR DESCRIPTION
**Pull request by SaptakS**
#2019 

fireshot capture 45 - settings - open event - http___localhost_5000_admin_settings_

@mariobehling please review.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please add the following info
* [ ] "Maintain Aspect Ratio" -> "Standard Aspect Ration is .... . Tick to maintain ratio."
* [ ] Add quality settings in  %
* [ ] Actually in the way you showing the config there is no need to enable the user to choose Icon/Thumbnail/Large - cause the user cannot change the size anyways as it would change the style, correct? 
   * [ ] So simply list the all pages that use a certain size below "Maintain Aspect Ratio"
   * [ ] Also add here information where on the page the image is located, e.g. the public event pages have the top background image, but there are also speaker images.
* [ ] Profile/Speaker images - I am not aware of any area where there is a large size. If there is none, then take out the configuration for that, please.

**Comment by mariobehling** [comment]
I think for profile/speaker images there are three sizes, but not the large one:
* [ ] Icon, e.g. top right profile image
screenshot from 2016-08-24 19 08 13


* [ ] Small, e.g. Event Dashboard speakers table http://open-event-dev.herokuapp.com/events/9/speakers/
screenshot from 2016-08-24 19 08 30

* [ ] Thumbnail, e.g. on public event page and on profile page
screenshot from 2016-08-24 19 09 07

**Comment by SaptakS** [comment]
@mariobehling will complete the things right away..

**Comment by SaptakS** [comment]
fireshot capture 46 - settings - open event - http___localhost_5000_admin_settings_

@mariobehling please check..

**Comment by mariobehling** [comment]
Thank you. Looks good. So, let's try out how this works in the live system. Cheers.

**Pull request merged**
