### PR TITLE
Fixes #4504

### LINKED ISSUE #4504: Typos in local.md
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

```sh
# Install and run redis
# For Ubuntu, Debian and alike
`sudo apt-get install redis-server`
# For Fedora, RedHat, CentOS
`sudo dnf install redis-server`

# Run Celery
# socketio has problems with celery "blocking" tasks
# also socketio is not used in a celery task so no problem to turn it off
`INTEGRATE_SOCKETIO=false celery worker -A app.celery`

# run app
`python manage.py runserver`
```
**Expected behavior:**

```sh
# Install and run redis
# For Ubuntu, Debian and alike

sudo apt-get install redis-server

# For Fedora, RedHat, CentOS

sudo dnf install redis-server

# Run Celery
# socketio has problems with celery "blocking" tasks
# also socketio is not used in a celery task so no problem to turn it off

INTEGRATE_SOCKETIO=false celery worker -A app.celery

# run app

python manage.py runserver
```
**Steps to reproduce:**

**Related code:**

```

```

**Other information:**

**System information:** 

```
Your operating system
```
Linux Ubuntu 16.04 LTS
```
output of `python --version`
```
python 2.7.12

> Would you like to work on it ?

Yes !

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes some Local md mistakes. Kindly review !

### CODE REVIEW

**Comment by shubham-padia** [comment]
I don't think these are mistakes, these quotes are meant for highlighting purposes. Kindly elaborate if there was any other reason of rectifying this :). Thanks.

**Comment by bhaveshAn** [comment]
@shubham-padia 
Earlier
```sh
# Install and run redis
# For Ubuntu, Debian and alike
`sudo apt-get install redis-server`
# For Fedora, RedHat, CentOS
`sudo dnf install redis-server`

# Run Celery
# socketio has problems with celery "blocking" tasks
# also socketio is not used in a celery task so no problem to turn it off
`INTEGRATE_SOCKETIO=false celery worker -A app.celery`

# run app
`python manage.py runserver`
```
After the PR:

```sh
# Install and run redis
# For Ubuntu, Debian and alike

sudo apt-get install redis-server

# For Fedora, RedHat, CentOS

sudo dnf install redis-server

# Run Celery
# socketio has problems with celery "blocking" tasks
# also socketio is not used in a celery task so no problem to turn it off

INTEGRATE_SOCKETIO=false celery worker -A app.celery

# run app

python manage.py runserver
```
Yes these are for highlighting purposes, but it becomes more simple, clear and convienient for pasting the command. Thanks !

**Comment by rahuldecoded** [comment]
Create an issue before raising a PR. Kindly follow [this](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/).

**Comment by bhaveshAn** [comment]
Fixes #4504 
@niranjan94  please check the issue and PR. Thanks 
> please follow best practices and create an issue first. Link the pr to the issue, add a proper commit message and pr title.

Yes, I will keep in mind, from now.
Thanks !

**Pull request merged**
