### PR TITLE
Show all events tab added

### LINKED ISSUE #789: Change color for :hover on Tabs
screenshot from 2016-06-14 01 36 36

As you can see, on hovering a tab the text color becomes white.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #789 #715 
fireshot capture 16 - events - open event - http___127 0 0 1_5000_events_

@mariobehling review

### CODE REVIEW

**Comment by rafalkowalski** [comment]
@SaptakS do we need all user events or all events from application?

**Comment by mariobehling** [comment]
@rafalkowalski Yes, this "all events" should depend on the role. it is only for super admins.

**Comment by rafalkowalski** [comment]
@mariobehling thanks

**Comment by SaptakS** [comment]
@rafalkowalski This tab shows all events created by all organizers. Not only the logged in organizer.. 
See here: https://github.com/fossasia/open-event-orga-server/issues/715

**Comment by mariobehling** [comment]
Well, currently everyone is a super admin as we dont have roles based permissions yet.

**Comment by SaptakS** [comment]
@mariobehling agreed.. As till now the roles and permissions haven't been implemented yet, so its being shown for all users.

**Comment by SaptakS** [comment]
So should we merge this PR or modify it after roles and permissions are implemented?

**Comment by rafalkowalski** [comment]
@SaptakS I think we can merge it

**Pull request merged**
