### PR TITLE
Allow users to either choose Ticket URL or ticketing system

### PR DESCRIPTION
**Pull request by aditya1702**
#1841

### CODE REVIEW

**Comment by aditya1702** [comment]
@mariobehling Please review

**Comment by niranjan94** [comment]
@aditya1702 please fix the codacy issues

**Comment by mariobehling** [comment]
If the user switches off the ticketing module, does the form go back to show the Ticket URL only?

**Comment by aditya1702** [comment]
@mariobehling Yes

**Comment by aditya1702** [comment]
@mariobehling Yes

**Pull request merged**
