### PR TITLE
Rearranged .md files and placed them in docs/  folder

### PR DESCRIPTION
**Pull request by aditya1702**
1. Rearranged .md files and placed them in docs/ folder
2. Added documentation regarding how to run tests for open-event server

### CODE REVIEW

**Comment by aditya1702** [comment]
@juslee Please review

**Comment by juslee** [comment]
License and readme remains in the root.

**Comment by aditya1702** [comment]
@juslee Done :smile:

**Comment by juslee** [comment]
Update the docs to follow the same installation guide as https://github.com/loklak/loklak_server.

Preferably if you actually do the steps.

Remove the Installation steps in README and reference the Installation section in README to the various installation MD.

**Comment by aditya1702** [comment]
@juslee Done. Edited Readme just like the one in loklak server repo

**Comment by aditya1702** [comment]
@juslee please review

**Comment by aditya1702** [comment]
Fixes #295 and #273

**Comment by aditya1702** [comment]
@juslee I think this can be merged

**Pull request closed without merging**
