### PR TITLE
Fix is_user_itself error

### LINKED ISSUE #4079: Trying to access (is_user_itself) permission for endpoints "any/<any_id>/user" gives KeyError: 'id'
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Reproduce:**

Example: `/users-events-roles/<int:users_events_role_id>/user` or `/event-invoices/<int:event_invoice_id>/user`

**Reason for error:**
check for `user.id != kwargs['id']` in permission

### PR DESCRIPTION
**Pull request by magdalenesuo**
Fixes #4079 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Changes:
- Fixes is_user_itself error
- Removes Access Code relationship with user

### CODE REVIEW

**Comment by magdalenesuo** [comment]
@fossasia/open-event-devs I could only do this way. If any of you have better approach for the permission, please feel free to change.

**Comment by poush** [comment]
Please see https://docs.google.com/document/d/1L-EsfeOWFNJQoGg_xdoiY-DYoKb-aD5wPCM0LBFfT8E/edit#bookmark=id.g0qrtyyhcbk8 I think it can explain more on permission manager model fetching part.

**Comment by magdalenesuo** [comment]
@poush Thanks :+1:

**Comment by magdalenesuo** [comment]
@poush  Adding this `decorators = (api.has_permission('is_user_itself', fetch="user_id", fetch_as="id", model=Notification, fetch_key_url="notification_id"),)` only works for notifications now.
How does it go about for `UsersEventsRoles`, `EventInvoice`, `AccessCodes` and `EmailNotification` at once?
Doing now makes model specific, giving error on `users/<id>` now.

**Comment by magdalenesuo** [comment]
@poush Your changes worked :) I made the changes here accordingly, can you review now?

**Pull request merged**
