### PR TITLE
add option to get session and speaker by id

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

Conflicts:
	open_event/views/views.py

### CODE REVIEW

**Comment by championswimmer** [comment]
@rafalkowalski please take a look :)

**Comment by leto** [comment]
This seems to be broken in a few ways. You are overriding two existing function names which cause it to not start:

```
AssertionError: View function mapping is overwriting an existing endpoint function: .get_speakers
AssertionError: View function mapping is overwriting an existing endpoint function: .get_sessions
```

I suggest changing those to `.get_session` and `.get_speaker` since you are returning data about a single entity. I made those changes to see if it would work and then got this:

```
Exception on /api/v1/event/1/speakers/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 127, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: get_speaker() got an unexpected keyword argument 'speaker_id'
```
Please test things more when sending a PR. It doesn't seem possible that this code worked on your local system. Also, give some example curl/wget requests with PR's that change the API, so it makes it easier for the reviewer. Soon we will have a test suite and all PR's changing the API will require tests, so that is good practice.

**Comment by championswimmer** [comment]
@leto Sorry, it was a mistake in git add. 
I ran git add and then made some more corrections, which didn't get picked. 

I have corrected it now. Please take a look

**Comment by aditya1702** [comment]
@championswimmer  This returns an error : **TypeError: get_session_by_id() got an unexpected keyword argument 'event_id'**
I suggest removing <int:event_id> from the url. Also after removing it I get an error :
 **AttributeError: 'Session' object has no attribute 'filter_by'**

**Comment by championswimmer** [comment]
What endpoint did you try?

**Comment by aditya1702** [comment]
@championswimmer I tried the same endpoint which you added 
'/api/v1/event/<int:event_id>/sessions/<int:session_id>'

**Comment by aditya1702** [comment]
Closing #233. Problem is fixed by PR #236

**Pull request closed without merging**
