### PR TITLE
Fixed travis build

### PR DESCRIPTION
**Pull request by aviaryan**
This PR fixes Travis build error.

### Comments

* cb6bcbb - This project was not compatible with Python 3+ so I removed all other python versions. Furthermore assuming that we all are using Python 2.7 and the same will be used on Heroku, I have only kept v2.7. Please correct me if I am wrong. 

See https://travis-ci.org/aviaryan/open-event-orga-server/builds/123264147 for the travis build log of my fork.

### CODE REVIEW

**Comment by aviaryan** [comment]
From https://github.com/fossasia/open-event-orga-server/issues/243#issuecomment-210345122
> On the other hand, 7 tests are failing both locally and on travis cloud but that can be fixed.

**Comment by mananwason** [comment]
@aviaryan Can you please squash commits? Also what's the point of this PR, the build is still failing.

**Comment by aviaryan** [comment]
@mananwason 
Currently the build (testcases) is/are not even running. The status is "build error". 
With this PR, the build is running but the testcases are failing.

**Comment by mananwason** [comment]
Oh okay fine. Please squash the commits please. cheers!

**Comment by aviaryan** [comment]
Okay sure :smile:

**Comment by juslee** [comment]
Test fails. Rewrite and make it pass.

**Comment by aviaryan** [comment]
@juslee Which "test" you mean ?
The current travis integration on this repo is broken and that is the reason all these PR's are failing. This PR fixes the travis integration for the open-event-orga-server. 

As quoted above
> Currently the build (testcases) is/are not even running. The status is "build error".
With this PR, the build is running but the testcases are failing.

**Comment by juslee** [comment]
Issue #243 is still open. I'll merge. fix the remaining tets.

**Comment by aviaryan** [comment]
okay. on it

**Comment by juslee** [comment]
After checking the changed files, I will not merge this PR.

**Comment by shivamMg** [comment]
@juslee Because of the renamed file?

**Comment by aviaryan** [comment]
@shivamMg That was an issue with nose itself. The file can't be named 'setup' otherwise it took it as a callable.

**Comment by shivamMg** [comment]
Yup! I read your link. This must be taken care of before working on the written tests. I've already worked on the written tests though (https://github.com/fossasia/open-event-orga-server/pull/245).

**Comment by aviaryan** [comment]
Yes, your PR will be helpful in making all the tests pass and then hopefully we can have this merged.

**Comment by aviaryan** [comment]
All tests are passing now. :tada: 
Travis build link https://travis-ci.org/aviaryan/open-event-orga-server/builds/123295581

@juslee

**Comment by juslee** [comment]
@aviaryan submit a new PR

**Comment by aviaryan** [comment]
Okay

**Comment by aviaryan** [comment]
Opened #247

**Comment by shivamMg** [comment]
@aviaryan Have you written the tests too?

**Comment by aviaryan** [comment]
5 or 6 of them were failing because of bad input. I took help from your PR and fixed them. :grimacing:  Thanks.

**Comment by shivamMg** [comment]
NP :+1:

**Pull request closed without merging**
