### PR TITLE
Add Better Quality Placeholder Images

### PR DESCRIPTION
**Pull request by PolBaladas**
https://github.com/fossasia/open-event-orga-server/issues/1845
#1845

### CODE REVIEW

**Comment by PolBaladas** [comment]
Okay! Images were actually ranging from 1MB to 15MB each but i used a quick script to reduce quality. I guess that was okay since server overload is not good 😂

**Comment by PolBaladas** [comment]
Hi there @niranjan94 I've updated static.py (again, scripted it). 
Thing is, although there are lots of good pics now, there are subjects where it's difficult to get good looking, license free and "neutral"

Examples:
Channukah
Republican Party
Non-Partisan
...

**Comment by PolBaladas** [comment]
As mentioned in https://github.com/fossasia/open-event-orga-server/issues/1845, Images are license-free!

**Comment by mariobehling** [comment]
@PolBaladas Thanks.

> As mentioned in #1845, Images are license-free!

Exactly this should be mentioned in regards to the license "Public Domain" with the link to the original in case questions about this ever come up. Cheers.

**Comment by mariobehling** [comment]
Ok, in order to get merged what has been done so far I am merging.
@PolBaladas Would be great if you could help to address the open points. Cheers.

**Comment by PolBaladas** [comment]
Yeah, Thanks @mariobehling. Sorry I've been sick for a couple of days now, not feeling well enough to code or even look @ a screen (you know me, that's serious :joy:)

Are these the open points you were talking about?
Open Points:

- [ ] Link to the original image/License
- [ ] App/helpers/static.py, there seem to be 3 entries missing

**Comment by mariobehling** [comment]
@PolBaladas Yes, thanks.

I have added them here: https://github.com/fossasia/open-event-orga-server/issues/2657

Hope you get better! Take care of yourself!

**Comment by PolBaladas** [comment]
Okay @mariobehling Thanks.
Shall we close this thread and discuss in #2657 ?
Thanks, Will do.

**Pull request merged**
