### PR TITLE
Added infobox which opens on clicking a session

### LINKED ISSUE #1635: Scheduler: Show more info about session on click
Parent: [#1564 (Comment)](https://github.com/fossasia/open-event-orga-server/issues/1564#issuecomment-232690851)

### PR DESCRIPTION
**Pull request by niranjan94**
Resolves #1635

@rafalkowalski @mariobehling @SaptakS please review and merge

### CODE REVIEW

**Comment by mariobehling** [comment]
@niranjan94 Please resolve conflicts. Please give us a screenshot.

**Comment by niranjan94** [comment]
@mariobehling Conflicts have been resolved 

capture

**Comment by mariobehling** [comment]
Looks good, but cannot test at the moment. Sessions are not loading https://open-event-dev.herokuapp.com/e/9/schedule/

**Comment by SaptakS** [comment]
@mariobehling scheduler is working now.

**Pull request merged**
