### PR TITLE
Updated access code api docs

### LINKED ISSUE #4456: Update docs for the access codes API.
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Update the docs for the access codes API.

### PR DESCRIPTION
**Pull request by rahuldecoded**
Fixes #4456 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.

Let me know if further modification is required.

### CODE REVIEW

**Comment by shubham-padia** [comment]
@rahuldecoded please compare the docs with the schema and make sure you add the relationships present in the schema but missing in the docs

**Comment by rahuldecoded** [comment]
@shubham-padia I did as you said. For me details are already there in docs according to the schema but the `valid-till` and `valid-from` are the compulsory attribute without anyone user will get `500 Internal Server Error` message so these should be mentioned as compulsory field in docs. Kindly tell me if I left something.
screenshot from 2017-09-27 16-42-15
screenshot from 2017-09-27 16-42-15

**Comment by shubham-padia** [comment]
Tickets relationship is missing from the docs. Also, for comparing schema, rather than psql, looking up the files in the api/schema is encouraged

**Comment by rahuldecoded** [comment]
@shubham-padia 
I've seen this
screenshot from 2017-09-28 02-07-45
and tried to do this
screenshot from 2017-09-28 02-15-52
but got an error.
screenshot from 2017-09-28 02-13-08
and currently I'm having a doubt is that we've `tickets-number` in attributes then why we need to add a ticket relationship.

**Pull request merged**
