### PR TITLE
Sponsors added to event creation wizard

### PR DESCRIPTION
**Pull request by SaptakS**
#697

### CODE REVIEW

**Comment by SaptakS** [comment]
@rafalkowalski please review
screenshot from 2016-06-11 22 08 14
screenshot from 2016-06-11 22 08 27

**Comment by mariobehling** [comment]
@SaptakS Sponsorship form is not implemented as needed. It must be possible to add more than one sponsor. The set of fields is for one sponsor only. It must be possible to have more sets.

**Comment by mariobehling** [comment]
Please use correct spelling: URL 
(in capitals)

**Comment by SaptakS** [comment]
@mariobehling working on more sets.. And sorry for the spelling.

**Pull request merged**
