### PR TITLE
added unverified user and total number of users #3110

### LINKED ISSUE #3110: Admin Panel: Show detailed user numbers
In the admin panel there is a widget with a table "System Roles". Please improve as follows:

* [ ] Add Row "Unverified User"
* [ ] On the last row show "Total No. of Users"

screenshot from 2017-02-01 11-25-18

### PR DESCRIPTION
**Pull request by Himanshi-Khandelwal**
unverified user and total number of users . The two rows are added .Please review :)

Resolves #3110

### CODE REVIEW

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal there is a merge conflict at `app/templates/gentelella/admin/super_admin/widgets/_users.html` .. Please resolve it. And squash all the commits into one.

**Comment by Jatinbalodhi96** [comment]
you have conflicting file

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94  @Jatinbalodhi96  I am not getting what is the conflict ? Why is it a conflicting file?

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal a file conflict occurs while merging when a same line in the same file is modified on the branch into which you're merging into and by you.

You can prevent this from occurring by first pulling all the latest changes from the development before making your modifications. 

To fix this, you can merge the `development` branch from this repo into your local branch. And then goto `app/templates/gentelella/admin/super_admin/widgets/_users.html` and edit the file such that what needs to be there stays.

For more info, https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by Jatinbalodhi96** [comment]
you need to update forked repo [Check this out](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Pull request closed without merging**
