### PR TITLE
feat(schedule): Move schedule to lightbox

### LINKED ISSUE #3273: Add pop out feature and icon for lightbox of schedule
The pop out feature to open a lightbox is a common element in many applications e.g. in Gmail.

screenshot from 2017-02-27 22-03-32

Add the icon to access this feature to the schedule on the right-hand side next to "Session View".

Open the schedule in a lightbox with white background and a closing icon again next to "Session View" to the top right to "pop in" the window.

screenshot from 2017-02-27 22-05-26

### PR DESCRIPTION
**Pull request by uttu357**
- Open schedule in light box on event homepage.
- Pop Up schedule on clicking on remove button.

screenshot from 2017-03-03 18 47 18

Fixes #3273

Please review.. :)

### CODE REVIEW

**Comment by niranjan94** [comment]
@uttu357 please provide a test deployment where this can be tested

**Comment by mariobehling** [comment]
@uttu357 Thank you. Could you leave the schedule page intact and provide this feature as a pop out similar to gmail emails, please?

**Comment by uttu357** [comment]
@mariobehling Sure.. :+1:

**Comment by uttu357** [comment]
@niranjan94 http://ec2-52-37-57-225.us-west-2.compute.amazonaws.com/e/fb402de5/#schedule
Set up the test deployment server...

**Comment by uttu357** [comment]
@mariobehling Made the required changes. Please review.

Live at http://ec2-52-37-57-225.us-west-2.compute.amazonaws.com/e/fb402de5/schedule/

screenshot from 2017-03-04 00 49 21
screenshot from 2017-03-04 00 49 42

**Comment by mariobehling** [comment]
Thank you.

* Please move the pop in/pop out button on the right hand side next to the "Sessions View"
* The heading of the pop out should be the line below "Schedule" -> the dates. There is no need for the "Schedule" heading on the pop out itself.
* The example of Google was about the feature. There is no need to change the styling and create a dark top bar. Just keep the existing design, please for now.
* Please make the pop out use 100% of the screen size -> This is the whole point of the issue: To use 100% of the screen.

**Comment by mariobehling** [comment]
Could you also test this feature on mobile, please?

**Comment by uttu357** [comment]
Sure I will make the required changes.. :+1:

**Comment by uttu357** [comment]
Made the required changes.
screenshot from 2017-03-05 23 02 42
On mobile
screenshot from 2017-03-05 23 30 04
Changes are live at http://ec2-52-37-57-225.us-west-2.compute.amazonaws.com/e/fb402de5/schedule/
@mariobehling Please review.. :)

**Comment by mariobehling** [comment]
@uttu357 Thanks for the improvements. The implementation is not fully functional yet. Currently there is a scroll bar on the bottom that is not full width and there is an empty column. Could you please check and help to solve the issue? Cheers: https://github.com/fossasia/open-event-orga-server/issues/3304

**Pull request merged**
