### PR TITLE
Speaker fields, level and speaking experience added

### LINKED ISSUE #2782: Add more fileds to "Collect Speaker Details" on Wizard Step 3
Please offer the collection of the following as well:
* [ ] City
* [ ] Sponsorship Required

### PR DESCRIPTION
**Pull request by magdalenesuo**
fixes #2782 , #2784 , #2785 

screenshot from 2016-12-31 17-13-27
screenshot from 2016-12-31 18-01-55

backend, input getting saved:
screenshot from 2017-01-02 19-50-28

### CODE REVIEW

**Comment by SaptakS** [comment]
@magdalenesuo good work in the frontend. Hoping backend work will be done soon as well.

**Comment by mariobehling** [comment]
@magdalenesuo How is it going?

**Comment by magdalenesuo** [comment]
@mariobehling working on the backend. sorry for the delay. Will complete it by tonight

**Comment by mariobehling** [comment]
@SaptakS @magdalenesuo Thank you. Please point me to where this has been implemented in the API. I could not find the info here: http://open-event-dev.herokuapp.com/api/v2/

**Comment by SaptakS** [comment]
@mariobehling, the api needs to be looked into separately. I am looking into that. I will make a separate issue for API and implement.  Need to check some other features in API.

**Pull request merged**
