### PR TITLE
Added Password Reset functionality

### PR DESCRIPTION
**Pull request by aditya1702**

### CODE REVIEW

**Comment by aditya1702** [comment]
@rafalkowalski @SaptakS Working. can be merged..please review

**Comment by SaptakS** [comment]
This is "Password Reminder" or "Password Reset"? Why reminder?

**Comment by rafalkowalski** [comment]
@aditya1702 please add tests

**Comment by aditya1702** [comment]
@rafalkowalski I will add the tests at the end. After I have added the google and facebook login. I will create a separate PR for it.

**Pull request merged**
