### PR TITLE
fix issue Increase width of ticketing form #2902

### LINKED ISSUE #2902: Increase width of ticketing form
The ticket sales form is breaking lines for long ticket names, but there is still some space left in the area.

Please increase the width of the form. Ensure it does not look too squeezed though.

screenshot from 2017-01-10 11-31-59

### PR DESCRIPTION
**Pull request by Rohanhacker**
should fix #2902

### CODE REVIEW

**Comment by SaptakS** [comment]
@Rohanhacker please attach associated screenshots after the changes you have made for better reviewing of your PR. Thanks.

**Comment by Abhi2424shek** [comment]
Previews pls

**Comment by niranjan94** [comment]
Tested locally. Looks good.

**Comment by mariobehling** [comment]
Please check my comment here: https://github.com/fossasia/open-event-orga-server/issues/2902#issuecomment-271760361

**Pull request merged**
